
const ImageAsset = {
    showcasePlain: "../src/assets/imgs/showcase_plain.png",
    showcaseBlumb: (index: number) => `../src/assets/imgs/blumb${index}.png`,
    showcaseBlumb1: "../src/assets/imgs/blumb1.png",
    showcaseBlumb2: "../src/assets/imgs/blumb2.png",
    showcaseBlumb3: "../src/assets/imgs/blumb3.png",
    showcaseBlumb4: "../src/assets/imgs/blumb4.png",
    showcaseBlumb5: "../src/assets/imgs/blumb5.png",
    showcaseBlumb6: "../src/assets/imgs/blumb6.png",
    showcaseBlumb7: "../src/assets/imgs/blumb7.png",
    showcaseBlumb8: "../src/assets/imgs/blumb8.png",
    showcaseESTR: (index: number) => `../src/assets/imgs/estr${index}.png`,
    showcaseESTR1: "../src/assets/imgs/estr1.png",
    showcaseESTR2: "../src/assets/imgs/estr2.png",
    showcaseESTR3: "../src/assets/imgs/estr3.png",
    showcaseESTR4: "../src/assets/imgs/estr4.png",
    showcaseObatin: (index: number) => `../src/assets/imgs/obatin${index}.png`,
    showcaseObatin1: "../src/assets/imgs/obatin1.png",
    showcaseObatin2: "../src/assets/imgs/obatin2.png",
    showcaseObatin3: "../src/assets/imgs/obatin3.png",
    showcaseObatin4: "../src/assets/imgs/obatin4.png",
    showcaseMoloco: (index: number) => `../src/assets/imgs/moloco${index}.png`,
    showcaseMoloco1: "../src/assets/imgs/moloco1.png",
    showcaseMoloco2: "../src/assets/imgs/moloco2.png",
    showcaseMoloco3: "../src/assets/imgs/moloco3.png",
    showcaseMoloco4: "../src/assets/imgs/moloco4.png",
    iconBlumb: "../src/assets/imgs/icon_blumb.png",
    iconObatin: "../src/assets/imgs/icon_obatin.png",
    iconMoloco: "../src/assets/imgs/icon_moloco.png",
    iconESTR: "../src/assets/imgs/icon_estr.png",

}
export default ImageAsset;